### ISSUE TITLE
Fault on underflow with sub op code.

### ISSUE THREAD

**Issue by rlstrand** [kidmirage/KENBAK-2-5-Build-Files#1]
In the existing code:
    # Perform the subtraction.
    memory[register] -= operand;

When the result is negative Python throws VallueError 

This code seems to make it work:

    # Perform the subtraction.
    memory[register] = ((memory[register] - operand) + 256) & 0b11111111;

Without the '+ 256',  I still got the fault

;Example test case, step through this:
	load    A,2
top	sub     A,1
	jmp     top

Error log from console:

pi@pi47inch:~/KENBAK-1 $ python3 KENBAK-IDE.py 
Traceback (most recent call last):
  File "KENBAK-IDE.py", line 1632, in <module>
    if perform_next_instruction() == False:
  File "KENBAK-IDE.py", line 724, in perform_next_instruction
    process_sub()
  File "KENBAK-IDE.py", line 595, in process_sub
    memory[register] = (memory[register] - operand) & 0b11111111;
ValueError: byte must be in range(0, 256)
pi@pi47inch:~/KENBAK-1 $ python3 KENBAK-IDE.py

**Comment by kidmirage** [comment]
Thank you for taking the time to report this. This has been addressed in the latest release. My code was similar to yours:
  ```
  result = memory[register] - operand
  if result < 0: 
    result = (result * -1)|0b10000000
  memory[register] = result
```

Super happy to see someone looking at the IDE. Out of curiosity what are you doing with the KENBAK-1?

**Comment by kidmirage** [comment]
> if result < 0:
> result = (result * -1)|0b10000000
> memory[register] = result

**Comment by rlstrand** [comment]
I have an intrest in old computers.  I have been studing the theory of
operation of the Kenbak-1. I was writing some code to see how 16bit
math can be done inorder to write a pid control loop.  Not sure if
there will be enough ram.  I ave a nanoKenbak-1 from Addwaterandstir.
I see from some other sites that there is an emolation of bank
switched ram to allow for 1k of ram.  The pid control will poll the
input register for the sensor reading.  The reading will be in two
halves.  Bit 7 will indicate the order of the 7 bit halves.  Output
will be taken from bit 0 of the Output register.  Just a simle
application for the Kenbak to see it do ssomething useful.

I have started a gate level simulation based on the theory of
operation.  Run into some stumbling blocks on the notation.  May step
back and start the simulation at the state machine descrition.
Looking at getting to cycle accurate sim.

Your IDE will prove verry useful in developing the pid control.  Thank
you for your efforts.

Sending this from a limitted system sorry for any typos.

**Comment by kidmirage** [comment]
That sounds like a very cool project. I had a friend ask me if the KENBAK-1 could do any useful work. Well I would argue that a day of the week calculator is somewhat useful. I sent and Email to John Blankenbaker with a picture of my reproduction he was kind enough to reply. One thing he said was: " If you do a search on YouTube for John Blankenbaker you should be able to see and hear a talk I gave to to a computer historical society. One of the people there related that he had computed "e" to 84  decimal places on a Kenbak-1 computer. He stated that he checked the result against published values and it was correct."  A PID control  certainly useful. Good luck.

If there is anything you need from me don't hesitate to ask.

Mike
