### ISSUE TITLE
Shift Right may not match the Programming Manual

### ISSUE THREAD

**Issue by rlstrand** [kidmirage/KENBAK-2-5-Build-Files#2]
There may be a mismatch between the programming manual and the emulator.

From the manual:
SHIFT RIGHT 1 Original c7 c6 c5 c4 c3 c2 c1 c0
                             After c7 c7 c6 c5 c4 c3 c2 c1

It seem that the KENBAK-1 should sign extend on shift right.

The emulator does this:

SHIFT RIGHT 1 Original c7 c6 c5 c4 c3 c2 c1 c0
                             After  0 c7 c6 c5 c4 c3 c2 c1

Test code:
	load	A,255
	sft	A,R,1
	halt

**Comment by kidmirage** [comment]
Fixed in release V1.02.  I definitely missed this one.
