### ISSUE TITLE
Loading A,B,X with the address of a variable

### ISSUE THREAD

**Issue by rlstrand** [kidmirage/KENBAK-2-5-Build-Files#3]
I have a question on the assembler syntax.   How does one load the address of a variable into the X register.  If I use a constant integer it works, but I need to adjust the address by hand.  If I use the label for the variable I get the contents of the variable. 

Usually something like load X,#foo works in other assemblers.  The # indicated to load X with the address of foo.
Is this just missing feature?

**Comment by kidmirage** [comment]
Added in release V1.02. I had not thought to include this.  Great suggestion.
