### ISSUE TITLE
Subtract op code not working

### ISSUE THREAD

**Issue by rlstrand** [kidmirage/KENBAK-2-5-Build-Files#5]
load A,0
	sub  A,1
	halt

A gets set to 10000001

It should be set to 11111111

I think the code I provided in 
https://github.com/kidmirage/KENBAK-2-5-Build-Files/issues/1
should return the correct value

# Perform the subtraction.
memory[register] = ((memory[register] - operand) + 256) & 0b11111111;

**Comment by kidmirage** [comment]
Fixed in release V1.02.

**Comment by kidmirage** [comment]
Thank you for helping me make this project better,
