### ISSUE TITLE
Indexed addressing does not work

### ISSUE THREAD

**Issue by rlstrand** [kidmirage/KENBAK-2-5-Build-Files#6]
In the Indexed mode of addressing, the contents of the second
word of the instruction are added to the contents of the X Register to form
the address of the operand.

In the Indirect Indexed mode of addressing, the contents of the
second word of the instruction are used as an address pointer to the
contents of another, second, location, The contents of this second
location are added to the contents of the X Register to form the address
of the operand.

In get_address()

operand+memory[X] should be operand+X

memory[operand]+memory[X] should be memory[operand]+X

**Comment by kidmirage** [comment]
Actually since all of the "registers" are just in memory, I believe that
this code is correct. X in this case is defined as being a 2, the offset
into memory where the X register value resides. So memory[X] is the value
of the X register.

Mike

**Comment by rlstrand** [comment]
Yes you are correct, my mistake.
