### ISSUE TITLE
Feature request for db pseudo op code

### ISSUE THREAD

**Issue by rlstrand** [kidmirage/KENBAK-2-5-Build-Files#7]
It would be good if the db op code took an optional parameter to specify the number of bytes to reserve.  This is handy for my 16 bit variables.   Currently:

foo_lsb  db
foo_msb db

A 16 bit var:  foo  db 2
A byte array[16]:  array db 16

Optionally add other pseudo ops:

16 bit reserve:  dw [n]
32 bit reserve:  dlw [n]
64 bit reserve   dllw [n]

**Comment by kidmirage** [comment]
Good idea. You can now add the number of bytes to reserve,
